<?php

/*
 * Implement hook_preprocess_page
 */
function thp_preprocess_page(&$vars) {
  if ($vars['is_front']) {
    drupal_add_css(drupal_get_path('module', 'thp') . '/css/intro.css');
    drupal_add_js(drupal_get_path('module', 'thp') . '/js/intro.js');
  }
	drupal_add_css(drupal_get_path('module', 'thp') . '/css/tam.css');
  drupal_add_js(drupal_get_path('module', 'thp') . '/js/tam.js');
  drupal_add_css(drupal_get_path('module', 'thp') . '/css/thp.css');
  drupal_add_js(drupal_get_path('module', 'thp') . '/js/thp.js');
}

/*
 * Implement hook_preprocess_node
 */
function thp_preprocess_node(&$node) {
  
}